# Use root/example as user/password credentials

version: "11.6"
services:

  db:
    container_name: maria-db1
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    environment:
      MARIADB_ROOT_PASSWORD: root

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
